### ISSUE TITLE
SystemErrToLogging recipe doesn't work when method invocation occurs in a swtich-case block in some cases.

### ISSUE THREAD

**Issue by SunghwanJang** [openrewrite/rewrite-logging-frameworks#192]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.42.0
- rewrite-java v8.42.0
- rewrite-logging-frameworks v2.18.0

## What is the smallest, simplest way to reproduce the problem?

my unit test

```java
import static org.openrewrite.java.Assertions.java;
import static org.openrewrite.test.RewriteTest.toRecipe;

import org.junit.jupiter.api.Test;
import org.openrewrite.java.logging.SystemErrToLogging;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;

public class TemplateTestInSwithCase implements RewriteTest {
	
	@Override
	public void defaults(RecipeSpec spec) {
		spec.recipe(toRecipe(() -> new SystemErrToLogging(false, "logger", "SLF4J").getVisitor()));
	}

	@Test
	void replaceSystemErr() {
		rewriteRun(java("""
				public class A {
				  org.slf4j.Logger logger = null;
				  public void m() {
				    int cnt = 1;
				    String name = "";
				    switch (cnt) {
				      case 1 : 
						java.util.List<Integer> numbers = new java.util.ArrayList<>();
						numbers.forEach(o -> System.err.println(String.valueOf(o)));
				      break;
				      case 2 :
				        break;
				      case 3:
				        break;
				      default :
				        break;
				    }
				  }
				  public String m2(String s1) {
				    return null;
				  }
				}
			""", 
			"""
		"""));
	}
}
```

## What did you expect to see?

System.err.println replaced with logger

## What did you see instead?

java.lang.IllegalArgumentException: Could not parse as Java

## What is the full stack trace of any errors you encountered?

```
Caused by: org.openrewrite.internal.RecipeRunException: java.lang.IllegalArgumentException: Could not parse as Java
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:290)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:157)
	at org.openrewrite.java.JavaTemplate.apply(JavaTemplate.java:115)
	at org.openrewrite.java.logging.SystemErrToLogging$1.replaceMethodInvocation(SystemErrToLogging.java:155)
	at org.openrewrite.java.logging.SystemErrToLogging$1.logInsteadOfPrint(SystemErrToLogging.java:141)
	at org.openrewrite.java.logging.SystemErrToLogging$1.visitMethodInvocation(SystemErrToLogging.java:126)
	at org.openrewrite.java.logging.SystemErrToLogging$1.visitMethodInvocation(SystemErrToLogging.java:76)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3923)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:320)
	at org.openrewrite.java.JavaVisitor.visitLambda(JavaVisitor.java:795)
	at org.openrewrite.java.JavaIsoVisitor.visitLambda(JavaIsoVisitor.java:209)
	at org.openrewrite.java.JavaIsoVisitor.visitLambda(JavaIsoVisitor.java:30)
	at org.openrewrite.java.tree.J$Lambda.acceptJava(J.java:3191)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:320)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1367)
	at org.openrewrite.java.JavaVisitor.lambda$visitContainer$35(JavaVisitor.java:1417)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:243)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:265)
	at org.openrewrite.java.JavaVisitor.visitContainer(JavaVisitor.java:1417)
	at org.openrewrite.java.JavaVisitor.visitMethodInvocation(JavaVisitor.java:914)
	at org.openrewrite.java.JavaIsoVisitor.visitMethodInvocation(JavaIsoVisitor.java:229)
	at org.openrewrite.java.logging.SystemErrToLogging$1.visitMethodInvocation(SystemErrToLogging.java:119)
	at org.openrewrite.java.logging.SystemErrToLogging$1.visitMethodInvocation(SystemErrToLogging.java:76)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3923)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:320)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1367)
	at org.openrewrite.java.JavaVisitor.lambda$visitContainer$35(JavaVisitor.java:1417)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:243)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:265)
	at org.openrewrite.java.JavaVisitor.visitContainer(JavaVisitor.java:1417)
	at org.openrewrite.java.JavaVisitor.visitCase(JavaVisitor.java:428)
	at org.openrewrite.java.JavaIsoVisitor.visitCase(JavaIsoVisitor.java:98)
	at org.openrewrite.java.JavaIsoVisitor.visitCase(JavaIsoVisitor.java:30)
	at org.openrewrite.java.tree.J$Case.acceptJava(J.java:1087)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:320)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1367)
	at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:397)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:243)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:265)
	at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:396)
	at org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:88)
	at org.openrewrite.java.logging.SystemErrToLogging$1.visitBlock(SystemErrToLogging.java:79)
	at org.openrewrite.java.logging.SystemErrToLogging$1.visitBlock(SystemErrToLogging.java:76)
	at org.openrewrite.java.tree.J$Block.acceptJava(J.java:838)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:320)
	at org.openrewrite.java.JavaVisitor.visitSwitch(JavaVisitor.java:1115)
	at org.openrewrite.java.JavaIsoVisitor.visitSwitch(JavaIsoVisitor.java:290)
	at org.openrewrite.java.JavaIsoVisitor.visitSwitch(JavaIsoVisitor.java:30)
	at org.openrewrite.java.tree.J$Switch.acceptJava(J.java:5028)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:320)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1367)
	at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:397)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:243)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:265)
	at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:396)
	at org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:88)
	at org.openrewrite.java.logging.SystemErrToLogging$1.visitBlock(SystemErrToLogging.java:79)
	at org.openrewrite.java.logging.SystemErrToLogging$1.visitBlock(SystemErrToLogging.java:76)
	at org.openrewrite.java.tree.J$Block.acceptJava(J.java:838)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:320)
	at org.openrewrite.java.JavaVisitor.visitMethodDeclaration(JavaVisitor.java:875)
	at org.openrewrite.java.JavaIsoVisitor.visitMethodDeclaration(JavaIsoVisitor.java:224)
	at org.openrewrite.java.JavaIsoVisitor.visitMethodDeclaration(JavaIsoVisitor.java:30)
	at org.openrewrite.java.tree.J$MethodDeclaration.acceptJava(J.java:3669)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:320)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1367)
	at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:397)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:243)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:265)
	at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:396)
	at org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:88)
	at org.openrewrite.java.logging.SystemErrToLogging$1.visitBlock(SystemErrToLogging.java:79)
	at org.openrewrite.java.logging.SystemErrToLogging$1.visitBlock(SystemErrToLogging.java:76)
	at org.openrewrite.java.tree.J$Block.acceptJava(J.java:838)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:320)
	at org.openrewrite.java.JavaVisitor.visitClassDeclaration(JavaVisitor.java:482)
	at org.openrewrite.java.JavaIsoVisitor.visitClassDeclaration(JavaIsoVisitor.java:108)
	at org.openrewrite.java.JavaIsoVisitor.visitClassDeclaration(JavaIsoVisitor.java:30)
	at org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:1291)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:320)
	at org.openrewrite.java.JavaVisitor.lambda$visitCompilationUnit$9(JavaVisitor.java:495)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:243)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:265)
	at org.openrewrite.java.JavaVisitor.visitCompilationUnit(JavaVisitor.java:495)
	at org.openrewrite.java.JavaIsoVisitor.visitCompilationUnit(JavaIsoVisitor.java:113)
	at org.openrewrite.java.JavaIsoVisitor.visitCompilationUnit(JavaIsoVisitor.java:30)
	at org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1562)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:157)
	at org.openrewrite.Repeat$1.visit(Repeat.java:78)
	at org.openrewrite.Repeat$1.visit(Repeat.java:39)
	at org.openrewrite.Preconditions$Check.visit(Preconditions.java:175)
	at org.openrewrite.Preconditions$Check.visit(Preconditions.java:145)
	at org.openrewrite.scheduling.RecipeRunCycle.lambda$editSources$6(RecipeRunCycle.java:186)
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:147)
	at org.openrewrite.table.RecipeRunStats.recordEdit(RecipeRunStats.java:67)
	at org.openrewrite.scheduling.RecipeRunCycle.lambda$editSources$7(RecipeRunCycle.java:182)
	... 84 more
Caused by: java.lang.IllegalArgumentException: Could not parse as Java
	at org.openrewrite.java.internal.template.JavaTemplateParser.lambda$compileTemplate$13(JavaTemplateParser.java:267)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.openrewrite.java.internal.template.JavaTemplateParser.compileTemplate(JavaTemplateParser.java:267)
	at org.openrewrite.java.internal.template.JavaTemplateParser.lambda$parseBlockStatements$9(JavaTemplateParser.java:176)
	at org.openrewrite.java.internal.template.JavaTemplateParser.cacheIfContextFree(JavaTemplateParser.java:293)
	at org.openrewrite.java.internal.template.JavaTemplateParser.parseBlockStatements(JavaTemplateParser.java:171)
	at org.openrewrite.java.internal.template.JavaTemplateJavaExtension$1.maybeReplaceStatement(JavaTemplateJavaExtension.java:450)
	at org.openrewrite.java.internal.template.JavaTemplateJavaExtension$1.visitMethodInvocation(JavaTemplateJavaExtension.java:422)
	at org.openrewrite.java.internal.template.JavaTemplateJavaExtension$1.visitMethodInvocation(JavaTemplateJavaExtension.java:55)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3923)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	... 201 more
```

I debugged a 'org.openrewrite.java.internal.template.BlockStatementTemplateGenerator' class.

generated stub looks like this

```java
import org.openrewrite.java.internal.template.__M__;
import org.openrewrite.java.internal.template.__P__;
public class A{org.slf4j.Logger logger;
public void m(){
String name=null;

int cnt=0;
{
__M__.any(o ->{ if(true) {return
/*__TEMPLATE__*/__P__.<org.slf4j.Logger>/*__p0__*/p().error(__P__.<java.lang.String>/*__p1__*/p())/*__TEMPLATE_STOP__*/
;}
return null;
})}}
public String m2(String s1){
return null;
}
}
```

![image](https://github.com/user-attachments/assets/9c9b8f8d-7c0e-476d-b258-08b3757a0990)

**Comment by SunghwanJang** [comment]
when the method invocation is contained in a method block, it works.
and this stub contains a ';' after ')'.

```java
import org.openrewrite.java.internal.template.__M__;
import org.openrewrite.java.internal.template.__P__;
public class A{
public void m(){
__M__.any(o ->{ if(true) {return
/*__TEMPLATE__*/__P__.<org.slf4j.Logger>/*__p0__*/p().error(__P__.<java.lang.String>/*__p1__*/p())/*__TEMPLATE_STOP__*/
;}
return null;
});}
public String m2(String s1){
return null;
}
}
```

Therefore, even in this case, it seems correct that the stub is created as follows.

```java
import org.openrewrite.java.internal.template.__M__;
import org.openrewrite.java.internal.template.__P__;
public class A{
public void m(){
{
__M__.any(o ->{ if(true) {return
/*__TEMPLATE__*/__P__.<org.slf4j.Logger>/*__p0__*/p().error(__P__.<java.lang.String>/*__p1__*/p())/*__TEMPLATE_STOP__*/
;}
return null;
});}}
public String m2(String s1){
return null;
}
}
```

I couldn't take a closer look at  BlockStatementTemplateGenerator. But I think there is a problem with this.

**Comment by timtebeek** [comment]
Thanks for sharing those details @SunghwanJang ! Indeed I'm also suspecting that BlockStatementTemplateGenerator, which we should explore separately in openrewrite/rewrite. Just need to find the time to do so.
